### ISSUE TITLE
Form select text doesn't appear

### ISSUE THREAD

**Issue by Nayar** [iKreativ/Workless#30]
Here you can see the selected option

![image](https://cloud.githubusercontent.com/assets/454815/6663799/8e707adc-cbe3-11e4-992e-7c10ea2970d8.png)

**Comment by iKreativ** [comment]
It's showing, it just looks slightly out of place on Windows, the select text is 'Choose'. 

Wanna send a pull request?

**Comment by Nayar** [comment]
![image](https://cloud.githubusercontent.com/assets/454815/6671899/f8673c26-cc21-11e4-8a69-bd17f599a353.png)

I don't see it showing IMO.
